### 2025-09-24

### Numpy

In [ ]:
대수, 행렬, 통계 등 수학 및 과학 연산을 위한 라이브러리
ndarray라는 다차원 배열을 데이터로 나타내고 처리하는데 특화
실횅속도가 빠르고 짧고 간결한 코드 구현이 가능하다. 
Numpy는 외부 라이브러리이므로, 설치 후 사용할 수 있다.

In [1]:
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

In [6]:
np.__version__

'2.3.3'

In [8]:
L = range(1000)
%timeit L2 = [i ** 2 for i in L]

53.7 μs ± 7.2 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [9]:
arr = np.arange(1000)
%timeit arr2 = arr**2

1.09 μs ± 22.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [20]:
alist = [1, 2, 3, 4, 5, 6]

In [15]:
print(alist)
print(type(alist))

[1, 2, None, 4, 5, 6]
<class 'list'>


In [17]:
blist = [1, 2, None, 4, 5, 6]

In [25]:
ar1 = np.array(alist)
print(ar1)
print(type(ar1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [26]:
ar1.dtype

dtype('int64')

In [22]:
ar2 = np.array([1.1, 2.2, 3.3])

In [23]:
print(ar2)

[1.1 2.2 3.3]


In [24]:
ar2.dtype

dtype('float64')

In [29]:
# 모든 원소가 같은 타입이어야 한다. 
list_data = [1, 2., 3]

ar3 = np.array(list_data, dtype='int')

print(ar3)
print(ar3.dtype)

[1 2 3]
int64


In [30]:
np.array([1, 2, np.nan, 4])
# python의 None은 존재하지 않는다.
# numpy 의 nan은 데이터가 정의되지 않았음.(숫자가 아니라서 정의할 수 없음)

array([ 1.,  2., nan,  4.])

In [31]:
arr1 = np.array([1, 2, 3, 4])

print(arr1)
print(arr1.ndim)
print(arr1.shape)

[1 2 3 4]
1
(4,)


In [32]:
arr2 = np.array([[1, 2, 3, 4]])
                
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[1 2 3 4]]
2
(1, 4)


In [33]:
arr2  = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [38]:
arr3 = arr2.reshape(2, -1, 3) # 2행 3열짜리 depth 2개 생성해줘

print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)


In [41]:
alist = np.array([1, 2, 3, 4, 5])
blist = np.array([6, 7, 8, 9, np.nan])

In [43]:
blist

array([ 6.,  7.,  8.,  9., nan])

In [45]:
print(alist + 2)
print(alist - 2)
print(alist * 2)
print(alist / 2)

[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [47]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

(a == 2) & (b > 10)

array([False,  True, False])

In [49]:
a = np.array([0, 1, 2, 3, 4])
print(a[2])
print(a[-1])

2
4


In [55]:
alist = [[0, 1, 2], [3, 4, 5]]
# 0, 1, 5 출력하기

print(alist[0][0], alist[0][1], alist[1][2])

0 1 5


In [63]:
# [[0, 1, 2]
#  [3, 4, 5]]

# 0, 1 슬라이싱
print(alist[0][0:2])
# 4, 5 슬라이싱
print(alist[1][1:])
# 1, 4를 하나의 리스트에 담아서 보여주세요
[alist[0][1], alist[1][1]]

[0, 1]
[4, 5]


[1, 4]

In [67]:
blist = np.array([[0, 1, 2], [3, 4, 5]])
blist

array([[0, 1, 2],
       [3, 4, 5]])

In [75]:
blist[:, 1]

array([1, 4])

In [74]:
print(blist[0, :2])
print(blist[1, 1:])
print(blist[0, 1],blist[1, 1])

[0 1]
[4 5]
1 4


In [69]:
print(blist[0, 0], blist[0, 1], blist[1, 2])

0 1 5


In [76]:
print(blist[[0, 1], [1, 1]])

[1 4]


In [ ]:
# 배열 슬라이싱

a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

print(a[0, :3])
print(a[:, 1])
print(a[1, 1:])
print(a[:, :2])

[0 1 2]
[1 5]
[5 6 7]
[[0 1]
 [4 5]]


In [99]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
a

# 슬라이싱 최소 3회 도전

print(a[:, :2])

[[0 1]
 [4 5]
 [8 9]]


In [100]:
print(a[0, :], a[2, :])

[0 1 2 3] [ 8  9 10 11]


In [101]:
print(a[1:, 1:])

[[ 5  6  7]
 [ 9 10 11]]


In [103]:
print(a[:, 2:])

[[ 2  3]
 [ 6  7]
 [10 11]]


#### 팬시 인덱싱 : Fancy indexing

정수나 boolean을 이용해서 원하는 인덱스의 값만 꺼내서 가져오는 방식

In [104]:
a = np.array([0, 1, 2, 3, 4 , 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
                False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [105]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
idx = [0, 2, 5]
a[idx]

array([0, 2, 5])

In [106]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# 0번행과 2번행을 가져온다
b[[0, 2]] 

array([[1, 2, 3],
       [7, 8, 9]])

In [110]:
b[[0,1,2],[1,2,0]]

array([2, 6, 7])

In [111]:
# boolean 인덱싱
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [112]:
arr % 2 == 0

array([False,  True, False,  True, False,  True, False,  True])

In [ ]:
# 짝수인 숫자만 꺼내는 연산
arr[arr % 2 == 0]

array([2, 4, 6, 8])

In [ ]:
# 홀수인 숫자만 꺼내는 연산
arr[arr % 2 == 1]

array([1, 3, 5, 7])

In [ ]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
a[idx]
# 인덱스의 위치에 따라 여러번 출력된다.

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [116]:
a = np.array([[1, 2, 3 ,4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [122]:
a[:,[True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [123]:
a[:, [0, 3]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [124]:
a = np.array([[1, 2, 3 ,4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# 다시 확인해보기
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [129]:
data = np.array([1, 4, 9, 16])

In [130]:
np.sqrt(data)

array([1., 2., 3., 4.])

In [131]:
np.exp(data)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06])

In [ ]:
np.sum(data)

np.int64(30)

In [133]:
np.mean(data)

np.float64(7.5)

In [ ]:
np.std(data)

np.float64(5.678908345800274)

In [135]:
np.exp(data)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06])

In [137]:
# 도전 미션 
x = np.array([1, 2, 3, 4, 5, 6,7, 8, 9,10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# 배열에서 3의 배수 찾기 
# 배열에서 4로 나누면 1이 남는 수를 찾기
# 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾기
idx = x[(x % 3 == 0) & (x % 4 == 1)]
idx

array([9])

### Pandas

시리즈(Series)와 데이터 프레임(DataFrame)

In [140]:
!pip install pandas

   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
    --------------------------------------- 0.2/11.3 MB 6.3 MB/s eta 0:00:02
   --- ------------------------------------ 1.0/11.3 MB 12.2 MB/s eta 0:00:01
   --- ------------------------------------ 1.1/11.3 MB 11.2 MB/s eta 0:00:01
   -------- ------------------------------- 2.3/11.3 MB 13.3 MB/s eta 0:00:01
   -------- ------------------------------- 2.4/11.3 MB 12.9 MB/s eta 0:00:01
   ----------- ---------------------------- 3.2/11.3 MB 12.1 MB/s eta 0:00:01
   -------------- ------------------------- 4.1/11.3 MB 13.2 MB/s eta 0:00:01
   ----------------- ---------------------- 5.0/11.3 MB 13.8 MB/s eta 0:00:01
   ------------------- -------------------- 5.6/11.3 MB 14.2 MB/s eta 0:00:01
   ---------------------- ----------------- 6.5/11.3 MB 14.3 MB/s eta 0:00:01
   ------------------------- -------------- 7.3/11.3 MB 14.5 MB/s eta 0:00:01
   ---------------------------- ----------- 8.0/11.3 MB 14.7 MB/s eta 0:0


[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [141]:
import pandas as pd

In [243]:
df = pd.read_csv('heroes.csv') 
df


이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [145]:
pd.options.display.float_format = '{:.0f}'.format

In [146]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [147]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [ ]:
# 숫자형 데이터만 표기
df.describe()

나이   키             재산
count   7   7              5
mean   34 190  2300278000120
std    13  36  5142800956894
min    18 170            600
25%    26 172       50000000
50%    32 177      340000000
75%    39 184     1000000000
max    58 270 11500000000000

In [153]:
# 그냥 head를 하면 앞에서부터 5개 
df.head()
# tail은 뒤에서 다섯개
# df.tail()

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000

In [154]:
df['국적']

0       미국
1    아스가르드
2       미국
3    데미스키라
4       미국
5       미국
6      러시아
Name: 국적, dtype: object

In [155]:
type(df['국적'])

pandas.core.series.Series

In [156]:
df['국적'].unique()

array(['미국', '아스가르드', '데미스키라', '러시아'], dtype=object)

In [158]:
df['국적'].value_counts()

국적
미국       4
아스가르드    1
데미스키라    1
러시아      1
Name: count, dtype: int64

In [160]:
df['나이'].nsmallest()

2    18
5    25
3    27
6    32
4    33
Name: 나이, dtype: int64

In [161]:
df.nlargest(7, '나이')

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
6  블랙위도우  32    스파이    러시아  170       50000000
3   원더우먼  27     공주  데미스키라  178            NaN
5   캡틴마블  25    파일럿     미국  170      340000000
2  스파이더맨  18   고등학생     미국  177            600

In [162]:
df.nlargest(7, '키')

이름  나이     직업     국적    키             재산
4     헐크  33  핵물리학자     미국  270     1000000000
1     토르  45      신  아스가르드  190            NaN
3   원더우먼  27     공주  데미스키라  178            NaN
2  스파이더맨  18   고등학생     미국  177            600
0   아이언맨  58    CEO     미국  174 11500000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [165]:
# 1차원 데이터이므로 아래와 같이 인덱스 지정 가능
df['이름'][:5]

0     아이언맨
1       토르
2    스파이더맨
3     원더우먼
4       헐크
Name: 이름, dtype: object

In [167]:
df[:3]

이름  나이    직업     국적    키             재산
0   아이언맨  58   CEO     미국  174 11500000000000
1     토르  45     신  아스가르드  190            NaN
2  스파이더맨  18  고등학생     미국  177            600

In [168]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [ ]:
# df.iloc, df.loc
# iloc -> index 
# loc -> 

df.iloc[행 번호, 열 번호]

In [173]:
df.loc[1:3, ]

이름  나이    직업     국적    키  재산
1     토르  45     신  아스가르드  190 NaN
2  스파이더맨  18  고등학생     미국  177 600
3   원더우먼  27    공주  데미스키라  178 NaN

In [171]:
df.iloc[[1, 3, 6]]

이름  나이   직업     국적    키       재산
1     토르  45    신  아스가르드  190      NaN
3   원더우먼  27   공주  데미스키라  178      NaN
6  블랙위도우  32  스파이    러시아  170 50000000

In [174]:
df.iloc[:5, :3]

이름  나이     직업
0   아이언맨  58    CEO
1     토르  45      신
2  스파이더맨  18   고등학생
3   원더우먼  27     공주
4     헐크  33  핵물리학자

In [ ]:
df.loc[행 이름, 열 이름]

In [175]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [ ]:
# 모든 숫자의 범위를 포함한다.
df.loc[2:5]

이름  나이     직업     국적    키         재산
2  스파이더맨  18   고등학생     미국  177        600
3   원더우먼  27     공주  데미스키라  178        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
5   캡틴마블  25    파일럿     미국  170  340000000

In [179]:
df.loc[:2, ['이름', '직업']]

이름    직업
0   아이언맨   CEO
1     토르     신
2  스파이더맨  고등학생

In [180]:
df.loc[3:, '국적':'재산']

국적    키         재산
3  데미스키라  178        NaN
4     미국  270 1000000000
5     미국  170  340000000
6    러시아  170   50000000

In [181]:
df['나이'] > 30

0     True
1     True
2    False
3    False
4     True
5    False
6     True
Name: 나이, dtype: bool

In [182]:
df[df['나이'] > 30]

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [191]:
# 나이가 30 초과하면서 50 미만인 사람들의 전체 레코드
df[(df['나이'] > 30) & (df['나이'] < 50)]

이름  나이     직업     국적    키         재산
1     토르  45      신  아스가르드  190        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [196]:
df.loc[df['키'] >= 180, ['이름', '나이', '키']]

이름  나이    키
1  토르  45  190
4  헐크  33  270

In [197]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [210]:
# 컬럼 추가 
df['전투력'] = 98

In [ ]:
df['전투력'] = df['전투력'] - 5
df

이름  나이     직업     국적    키             재산  전투력
0   아이언맨  58    CEO     미국  174 11500000000000   93
1     토르  45      신  아스가르드  190            NaN   93
2  스파이더맨  18   고등학생     미국  177            600   93
3   원더우먼  27     공주  데미스키라  178            NaN   93
4     헐크  33  핵물리학자     미국  270     1000000000   93
5   캡틴마블  25    파일럿     미국  170      340000000   93
6  블랙위도우  32    스파이    러시아  170       50000000   93

In [ ]:
# 임시 삭제
# df.drop(columns=['전투력'])
# 진짜 삭제
df.drop(columns=['전투력'], inplace=True)

In [ ]:
df = df.drop(columns=['전투력'])

In [215]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [219]:
# 결측치
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [ ]:
# 결측치 확인
df['재산'].isnull()

0    False
1     True
2    False
3     True
4    False
5    False
6    False
Name: 재산, dtype: bool

In [ ]:
# boolean 인덱싱
df[df['재산'].isnull()]

이름  나이  직업     국적    키  재산
1    토르  45   신  아스가르드  190 NaN
3  원더우먼  27  공주  데미스키라  178 NaN

In [223]:
df.isnull().sum()

이름    0
나이    0
직업    0
국적    0
키     0
재산    2
dtype: int64

In [224]:
df.dropna()

이름  나이     직업   국적    키             재산
0   아이언맨  58    CEO   미국  174 11500000000000
2  스파이더맨  18   고등학생   미국  177            600
4     헐크  33  핵물리학자   미국  270     1000000000
5   캡틴마블  25    파일럿   미국  170      340000000
6  블랙위도우  32    스파이  러시아  170       50000000

In [225]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [278]:
df = df.fillna(method='ffill')
# 비어있으면 이전 값으로 채운다. 

C:\Users\EL064\AppData\Local\Temp\ipykernel_10132\2789684458.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='ffill')


In [279]:
df['재산'].fillna(df['재산'].mean())

0   11500000000000
1   11500000000000
2              600
3              600
4       1000000000
5        340000000
6         50000000
Name: 재산, dtype: float64

In [280]:
df.iloc[5, 1] = np.nan
df

이름  나이     직업     국적        키             재산
0   아이언맨  58    CEO     미국  174.0cm 11500000000000
1     토르  45      신  아스가르드  190.0cm 11500000000000
2  스파이더맨  18   고등학생     미국  177.0cm            600
3   원더우먼  27     공주  데미스키라  178.0cm            600
4     헐크  33  핵물리학자     미국  270.0cm     1000000000
5   캡틴마블 NaN    파일럿     미국  170.0cm      340000000
6  블랙위도우  32    스파이    러시아  170.0cm       50000000

In [281]:
# 캡틴마블의 결측치 채우기
# 나이의 평균값으로 결측치 채우기

df['나이'] = df['나이'].fillna(df['나이'].mean())

In [ ]:
# df['나이'].fillna(df['나이'].mean()) => 나이 컬럼값 중, 
# null인 셀에 나이 평균값을 채우고, 나이 컬럼만 존재하는 프레임을 반환
# df.fillna(df['나이'].mean()) => 모든 컬럼값 중, 
# null인 셀에 나이 평균값을 채우고, 모든 컬럼이 존재하는 프레임을 반환


In [282]:
df

이름  나이     직업     국적        키             재산
0   아이언맨  58    CEO     미국  174.0cm 11500000000000
1     토르  45      신  아스가르드  190.0cm 11500000000000
2  스파이더맨  18   고등학생     미국  177.0cm            600
3   원더우먼  27     공주  데미스키라  178.0cm            600
4     헐크  33  핵물리학자     미국  270.0cm     1000000000
5   캡틴마블  36    파일럿     미국  170.0cm      340000000
6  블랙위도우  32    스파이    러시아  170.0cm       50000000

In [249]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      float64
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(2), int64(1), object(3)
memory usage: 468.0+ bytes


In [283]:
def add_cm(height):
   return str(height) + 'cm'

def remove_cm(b):
   part = b.replace('cmcmcmcmcm', '')
   
   part_float = float(part)
   return str(part_float) + 'cm'

# 람다 활용
# df['키'].apply(lambda a: str(a) + 'cm')
# df = df['키'].apply(remove_cm)
df

이름  나이     직업     국적        키             재산
0   아이언맨  58    CEO     미국  174.0cm 11500000000000
1     토르  45      신  아스가르드  190.0cm 11500000000000
2  스파이더맨  18   고등학생     미국  177.0cm            600
3   원더우먼  27     공주  데미스키라  178.0cm            600
4     헐크  33  핵물리학자     미국  270.0cm     1000000000
5   캡틴마블  36    파일럿     미국  170.0cm      340000000
6  블랙위도우  32    스파이    러시아  170.0cm       50000000

In [284]:
# 기준별로 묶어준다.
df.groupby('국적')['재산'].mean()

국적
데미스키라              600
러시아           50000000
미국       2875335000150
아스가르드   11500000000000
Name: 재산, dtype: float64